name: Deploy to production server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Laravel Envoy
        run: composer -q global require laravel/envoy
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_ed25519"
          chmod 400 "$HOME/.ssh/id_ed25519"
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > "$HOME/.ssh/config"
          ssh-add "$HOME/.ssh/id_ed25519"
      - name: Deploy using Laravel Envoy
        run: $HOME/.composer/vendor/bin/envoy run deploy-production --commit="$GITHUB_SHA" --reponame="$GITHUB_REPOSITORY" --branch=master
